(()=>{
const style=document.createElement('style');style.textContent=`
.adminSection{margin-top:16px;border:1px solid var(--line);border-radius:14px;background:#0c1321;overflow:hidden}.adminSection summary{cursor:pointer;padding:13px 14px;font-weight:900;list-style:none}.adminSection summary::-webkit-details-marker{display:none}.adminSectionBody{padding:0 14px 14px}.risk{display:inline-flex;align-items:center;padding:4px 8px;border-radius:999px;font-size:11px;font-weight:900}.riskHigh{background:#3a151b;color:#ff9aa6}.riskMid{background:#3a2b14;color:#ffd07b}.riskLow{background:#123122;color:#79e2aa}.roleSelect{min-width:175px;margin:0;padding:8px;font-size:12px}.newSigningRow td{vertical-align:middle}.adminHint{padding:10px 12px;border-radius:10px;background:#111c2d;border:1px solid #263752;color:#c7d2e3;font-size:12px;line-height:1.45}.adminTools{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.adminTools input,.adminTools select{margin:0;max-width:260px}.rankTop{font-size:16px;font-weight:950;color:var(--accent)}
@media(max-width:640px){.roleSelect{min-width:145px}.adminSectionBody{padding:0 10px 12px}}
`;document.head.append(style);
const pin=document.querySelector('#pin');if(pin){pin.type='password';pin.autocomplete='current-password'}
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const roleLabel={ung_utvikling:'Ung utviklingsspiller',rolle_spiller:'Bredde / rolle-spiller',topp6:'Topp-6 / poengprodusent',offensiv_back:'Offensiv back',defensiv_back:'Defensiv back',veteran_profil:'Veteran / profil',keeper:'Keeper',ukjent:'Ikke satt'};
renderAdminAnalytics=async function(){
 const c=$('#adminAnalytics');if(!c)return;c.innerHTML='<div class="tiny">Laster analyse…</div>';
 try{
  const r=await fetch(ADMIN_API,{method:'POST',headers:{'content-type':'application/json','x-session-token':token},body:'{}'}),x=await r.json();if(!r.ok)throw Error(x.error||'Kunne ikke hente analyse');
  window.__adminAnalytics=x;
  const sync=x.lastSync,subs=x.submissions||[],logged=subs.filter(u=>u.hasLoggedIn).length,delivered=subs.filter(u=>u.seasonSubmitted).length;
  let html='<div class="analyticsgrid"><div class="metric"><span class="tiny">Har logget inn</span><b>'+logged+'/'+subs.length+'</b><span class="tiny">deltakere</span></div><div class="metric"><span class="tiny">Sesongtips levert</span><b>'+delivered+'/'+subs.length+'</b><span class="tiny">deltakere</span></div><div class="metric"><span class="tiny">Synk</span><b>'+(sync?.ok?'✓':'!')+'</b><span class="tiny">'+(sync?.finished_at?fmt(sync.finished_at):'ikke kjørt')+'</span></div></div>';
  html+='<details class="adminSection"><summary>👨‍👩‍👧‍👦 Deltakelse og leveringer</summary><div class="adminSectionBody">'+subs.map(u=>{const tip=u.seasonTip;const missing=(u.bonus||[]).filter(b=>!b.answered).map(b=>b.title);let d='<div class="playerline"><div><b>'+esc(u.name)+'</b><div class="tiny">'+(u.lastLogin?'Sist innlogget: '+fmt(u.lastLogin):'Har ikke logget inn ennå')+'</div></div><div style="text-align:right"><div class="'+(u.hasLoggedIn?'good':'cold')+'">'+(u.hasLoggedIn?'✓ Innlogget':'○ Ikke innlogget')+'</div><div class="tiny">'+(u.seasonSubmitted?'✓ Sesongtips':'○ Ikke levert')+' · Bonus '+u.bonusAnswered+'/'+u.bonusTotal+'</div></div></div>';if(tip)d+='<details class="adminDetails"><summary>Se levert tips</summary><div class="tiny" style="margin-top:8px"><b>Tabell:</b> '+(tip.table_tip||[]).map((t,i)=>(i+1)+'. '+esc(t)).join(' · ')+'<br><b>Trener:</b> '+esc(tip.coach_pick||'—')+'<br><b>Poengkonge:</b> '+esc(tip.points_pick||'—')+'<br><b>Verste ny-signering:</b> '+esc(tip.worst_pick||'—')+'<br><b>Positiv overraskelse:</b> '+esc(tip.positive_pick||'—')+'</div></details>';if(missing.length)d+='<details class="adminDetails"><summary>Mangler '+missing.length+' bonusoppgave(r)</summary><div class="tiny" style="margin-top:6px">'+missing.map(esc).join(' · ')+'</div></details>';return d}).join('')+'</div></details>';
  html+='<details class="adminSection"><summary>📊 Live EHL-tabell</summary><div class="adminSectionBody">'+(!(x.standings||[]).length?'<div class="notice">Ingen tabell tilgjengelig ennå.</div>':(x.standings||[]).map(s=>'<div class="playerline"><div><b>'+(s.position??'–')+'. '+esc(s.team)+'</b><div class="tiny">'+s.matches+' kamper · '+s.goals_scored+'–'+s.goals_conceded+' mål</div></div><div><b>'+s.total_points+' p</b></div></div>').join(''))+'</div></details>';
  const ns=x.newSignings||[];
  html+='<details class="adminSection" open><summary>👎 Kandidater til verste ny-signering</summary><div class="adminSectionBody"><div class="adminHint"><b>Dynamisk og rollejustert rangering.</b> En ung utviklingsspiller vurderes mildere enn en veteran/profil eller en spiller hentet for å produsere poeng. Live-statistikken kommer fra samme HockeyLive-synk som resten av appen. Listen er beslutningsstøtte, ikke automatisk fasit.</div><div class="adminTools"><input id="newSigningSearch" placeholder="Søk spiller eller lag"><select id="newSigningTeam"><option value="">Alle lag</option>'+[...new Set(ns.map(p=>p.team))].sort().map(t=>'<option>'+esc(t)+'</option>').join('')+'</select></div><div id="newSigningTable"></div></div></details>';
  html+='<details class="adminSection"><summary>🏒 Spilleranalyse</summary><div class="adminSectionBody">'+((x.players||[]).slice(0,20).map(p=>'<div class="playerline"><div><b>'+esc(p.name)+'</b><div class="tiny">'+esc(p.team)+' · '+p.games+' K · '+p.goals+' M · '+p.assists+' A</div></div><div style="text-align:right"><b>'+p.points+' p</b><div class="tiny">'+p.ppg.toFixed(2)+' P/K · ~'+p.projectedPoints+' p</div></div></div>').join('')||'<div class="notice">Ingen spillerdata ennå.</div>')+'</div></details>';
  c.innerHTML=html;
  const draw=()=>{const q=(c.querySelector('#newSigningSearch')?.value||'').toLowerCase(),team=c.querySelector('#newSigningTeam')?.value||'';const rows=ns.filter(p=>(!team||p.team===team)&&(!q||(p.name+' '+p.team).toLowerCase().includes(q)));const box=c.querySelector('#newSigningTable');if(!rows.length){box.innerHTML='<div class="notice">Ingen treff.</div>';return}box.innerHTML='<div style="overflow:auto"><table style="width:100%;border-collapse:collapse;min-width:980px;font-size:12px"><thead><tr style="text-align:left;color:var(--muted)"><th style="padding:8px">#</th><th style="padding:8px">Spiller</th><th style="padding:8px">Rolle/forventning</th><th style="padding:8px">K</th><th style="padding:8px">M</th><th style="padding:8px">A</th><th style="padding:8px">P</th><th style="padding:8px">P/K</th><th style="padding:8px">Risiko</th><th style="padding:8px">Valgt av</th></tr></thead><tbody>'+rows.map(p=>{const i=ns.indexOf(p),cls=p.riskScore>=70?'riskHigh':p.riskScore>=40?'riskMid':'riskLow',opts=(x.roleOptions||[]).map(o=>'<option value="'+esc(o.value)+'" '+(o.value===p.role?'selected':'')+'>'+esc(o.label)+'</option>').join('');return '<tr class="newSigningRow" style="border-top:1px solid var(--line)"><td style="padding:8px" class="rankTop">'+(i+1)+'</td><td style="padding:8px"><b>'+esc(p.name)+'</b><div class="tiny">'+esc(p.team)+(p.position?' · '+esc(p.position):'')+'</div><div class="tiny">'+esc(p.indicator)+'</div></td><td style="padding:8px"><select class="roleSelect" data-name="'+encodeURIComponent(p.name)+'" data-team="'+encodeURIComponent(p.team)+'">'+opts+'</select></td><td style="padding:8px">'+p.games+'</td><td style="padding:8px">'+p.goals+'</td><td style="padding:8px">'+p.assists+'</td><td style="padding:8px;font-weight:900">'+p.points+'</td><td style="padding:8px">'+(p.games?p.ppg.toFixed(2):'–')+'</td><td style="padding:8px"><span class="risk '+cls+'">'+p.riskScore+'/100</span></td><td style="padding:8px">'+p.chosenBy+'</td></tr>'}).join('')+'</tbody></table></div><div class="tiny" style="margin-top:8px">#1 = høyest aktuell risiko ut fra forventningsrolle, produksjon og tilgjengelighet. Tidlig i sesongen kan plasseringene flytte seg mye.</div>';box.querySelectorAll('.roleSelect').forEach(sel=>sel.onchange=async()=>{sel.disabled=true;try{const rr=await fetch(ADMIN_API,{method:'POST',headers:{'content-type':'application/json','x-session-token':token},body:JSON.stringify({action:'set_expectation',name:decodeURIComponent(sel.dataset.name),team:decodeURIComponent(sel.dataset.team),role:sel.value})});const z=await rr.json();if(!rr.ok)throw Error(z.error||'Kunne ikke lagre');await renderAdminAnalytics()}catch(e){alert(e.message);sel.disabled=false}})};
  c.querySelector('#newSigningSearch')?.addEventListener('input',draw);c.querySelector('#newSigningTeam')?.addEventListener('change',draw);draw();
 }catch(e){c.innerHTML='<div class="err">'+esc(e.message)+'</div>'}
};
setInterval(()=>{try{if(typeof D!=='undefined'&&D?.user?.is_admin&&!$('#adminView')?.classList.contains('hidden'))renderAdminAnalytics()}catch{}},60000);
})();